### ISSUE TITLE
Add yaml-based module loader

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#853]
I would like to retire `discretizers.disk` and replace it by a generic config file format. Something like

```yaml
type: StationaryModel
operator:
    type: LincombOperator
    operators:
        - L1.mat
        - L2.mat
    coefficients:
        - diffusion[0]
        - diffusion[1]
rhs: F1.mat
output_functional: C.mat
products:
    l2: l2.mat
    h1: h1.mat
parameters:
    diffusion:
        shape: 2
        range: [0.1, 10]
```

I haven't thought about the details yet, but the general idea would be to have a generic file format, which can be used to load arbitrary `Models` from disk. Any comments, @pymor/pymor-devs? I think one might also argue that the same could be achieved with few lines of Python code and that we actually do not need such functionality. 

If nobody disagrees, I would start by moving `discretizers.disk` to the `graveyard`.
